
---
platform: linux
inputs:
- name: stratos
outputs:
- name: image-tag
image_resource:
  type: docker-image
  source:
   repository:  splatform/ci-stratos-concourse
   tag: "latest"

run:
  path: bash
  args:
    - -exc
    - |
      cd stratos

      LATEST_TAG=$(cat package.json | grep version | grep -Po "([0-9\.]?)*")-$(git log -1 --format="%h")

      if [ ! -z ${TAG_SUFFIX} ]; then
        if [ "${TAG_SUFFIX}" != "null" ]; then
          LATEST_TAG=${LATEST_TAG}-${TAG_SUFFIX}
        fi
      fi

      ./build/store-git-metadata.sh

      cd ../image-tag
      echo "$LATEST_TAG" > v2-alpha-tag
      FILENAME="release-${LATEST_TAG}"
      cat > build-args << EOF
      { "stratos_version": "${LATEST_TAG}" }
      EOF

      cp stratos/.stratos-git-metadata.json ./ui-build-args

      
      tar -cf ${FILENAME}.tar v2-alpha-tag build-args ui-build-args
