---
platform: linux
inputs:
- name: stratos
outputs:
- name: image-tag
image_resource:
  type: docker-image
  source:
   repository:  ci-registry.capbristol.com:5000/alpine
   tag: "latest"
   insecure_registries: [ "ci-registry.capbristol.com:5000" ]

run:
  path: sh
  args:
    - -exc
    - |
      cd stratos
      LATEST_ALPHA_TAG=$(git for-each-ref --sort=taggerdate --format %\(tag\) refs/tags | grep alpha | tail -1)
      ALPHA_RELEASE_NUMBER=$(echo $LATEST_ALPHA_TAG | grep -o '...$')
      let ALPHA_RELEASE_NUMBER++
      if [ -n $ALPHA_RELEASE_NUMBER ]; then
        ALPHA_RELEASE_NUMBER='000'
      fi
      echo $ALPHA_RELEASE_NUMBER > image-tag/v2-alpha-tag