---
platform: linux
inputs:
- name: stratos
- name: helm-chart-tarball
- name: image-tag
image_resource:
  type: docker-image
  source:
   repository: splatform/ci-stratos-github-release
   tag: "latest"

run:
  path: sh
  args:
    - -exc
    - |
      # Create Github release
      ROOT_DIR=${PWD}
      cd ${ROOT_DIR}/stratos
      GIT_TAG=$(cat ../image-tag/v2-alpha-tag)
      git config --global user.name ${GIT_USER}
      git config --global user.email ${GIT_EMAIL}
      mkdir -p /root/.ssh/
      echo "${GIT_PRIVATE_KEY}" > /root/.ssh/id_rsa
      chmod 600 /root/.ssh/id_rsa
      echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      git tag -a ${GIT_TAG} -m "Alpha release of Stratos v2"
      git push --tags
      cd ${ROOT_DIR}/helm-chart-tarball
      CHART_PACKAGE=$(ls *.tgz)
      # Upload Helm chart to release
      github-release release -t ${GIT_TAG} --name "Stratos ${GIT_TAG} Preview release" --pre-release
      github-release upload -t ${GIT_TAG} --file ${CHART_PACKAGE} --name "console-v2-helm-chart-${GIT_TAG}.tgz"