---
platform: linux
inputs:
- name: stratos
- name: helm-chart-tarball
- name: image-tag
image_resource:
  type: docker-image
  source:
   repository: splatform/ci-stratos-github-release
   tag: "latest"

run:
  path: sh
  args:
    - -exc
    - |
      # Create Github release
      ROOT_DIR=${PWD}
      VERSION=$(cat image-tag/v2-version)
      cd ${ROOT_DIR}/stratos
      GIT_TAG="$(git describe $(git rev-list --tags --max-count=1))"
      cd ${ROOT_DIR}/helm-chart-tarball
      CHART_PACKAGE=$(ls *.tgz)
      # Upload Helm chart to release

      # Check that the release exists - if it does, don't create a new one
      set +e
      github-release info -t ${VERSION}
      RETVAL=$?
      set -e

      if [ $RETVAL -ne 0 ]; then
        github-release release -t ${VERSION} --name "Stratos ${VERSION} Preview release" --pre-release
      fi
      github-release upload -t ${VERSION} --file ${CHART_PACKAGE} --name "console-helm-chart-${GIT_TAG}.tgz"