---
platform: linux
inputs:
- name: stratos-ui
image_resource:
  type: docker-image
  source:
   # Image based on bosh/cli2 with git and go added
   repository:  irfanhabib/bosh-cli
   tag: "latest"

run:
  path: sh
  args:
    - -xc
    - |
      # Register BOSH Director
      apt-get update
      apt-get install -y git
      cat << EOF >> ca_cert
      $BOSH_CA_CERT
      EOF
      bosh2 alias-env vbox -e $BOSH_DIRECTOR_IP --ca-cert ca_cert
      export BOSH_CLIENT=admin
      export BOSH_CLIENT_SECRET=$BOSH_ADMIN_PASSWORD
      export BOSH_NON_INTERACTIVE=true

      # BOSH create release
      cd stratos-ui/stratos-ui-release

      bosh2 create-release
      # Delete any release
      bosh2 -e vbox upload-release -d stratos-ui

      # Upload built release
      bosh2 -e vbox upload-release -d stratos-ui
      # Deploy
      bosh2 -e vbox -d stratos-ui deploy bosh-lite/deployment.yml
      # List Deployment
      bosh2 -e vbox -d stratos-ui instances

      # Tear down deployment
      bosh2 -e vbox -d stratos-ui delete-deployment
      # Delete the release
      bosh2 delete-release stratos-ui -e vbox
