version: "2"
checks:
  method-complexity:
    config:
      threshold: 8
  method-lines:
    config:
      threshold: 40
  similar-code:
    config:
      threshold: 60
plugins:
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  scss-lint:
    enabled: true
exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*.d.ts"
