language: node_js
node_js:
  - "8.4"

branches:
  only:
    - travis

install:
- npm install

cache:
  directories:
  - "/home/travis/.npm/"

jobs:
  include:
  - stage: e2e Tests
    script:
    - npm run e2e
  - stage: Unit Tests
    script:
    - npm test
  - stage: Lint
    script:
    - npm build
    - npm run lint
