language: node_js
node_js:
- '8.4'
branches:
  only:
  - master
install:
- npm install
cache:
  directories:
  - "/home/travis/.npm/"
stages:
- Lint
- Unit Tests
jobs:
  include:
  - stage: Lint
    script:
    - npm run lint
  - stage: Unit Tests
    env:
    - CI_ENV=true
    - CC_TEST_REPORTER_ID=90a5c9072bb9f64db6b04d02cffc2061b036ff6975a6d0559daa83b19679091b
    before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script:
    - npm test
    after_script:
    - "./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT"
notifications:
  slack:
    rooms:
      secure: ElJe0CHQ9eCQRdaW2F/uhm384dwdQD6ZDLpcIU+GB3HyQadjCRzLm+YUTgtv1x2dtjRwshRjMhANNee8+lvAB2Ye87SCxhay45GcdwVALjIHI0L12A0tn51GbPkG9p8zNde+GbJyuFYuVJtuxsRtLMG9hM1sslqKBtGVAp4QLaYf8tVWnHocexqnwEV42FBAFlmKNrYuVFQblspZYcgrNhJjbTKMH4W8NtbqpuXvUsYJbw50dHtxi0kkMgWg7MSrnolD7bLCJ/idJUYyICwLYnfBt+kGqwREEFB+6WGJMnJ93ynT9uO6pik1TPiEcrf7uJzpSTnsxAfNtLuquaNO4Z9UPKq/teTJ/w6bXdEbsz11oPxtXXP+RxotFz0vT6w6+chjvlHUNhdba/qVlT4u7ea+OETtyGtr+9sI3r01zf5jzJdt1lRt/8KnbmaqMT8urj8nYSadV/4FYptXnYGeFivOx1B6gt/Cfi+5fuO/5FxQ+0ARPi4wsoE9BAPUP+LWhU8hM/zI/gPRqkHIu9a1F6oDvYaBxQP15Me6bECFSAA4id84NsYDBb33/J8d9qK5f/QLL86ulZyWb74p7XfSDq71VwtIqKcz8EMZEXRV9Kuf1Y1KqslQ9hEKAfdfFTh1Q7RjSoGBvzZMfVjOo8mZJp+b5i4yUoOmmRycXKTOyqU=
    on_success: always
