language: node_js
node_js:
  - "8.4"

branches:
  only:
    - travis

install:
- npm install

cache:
  directories:
  - "/home/travis/.npm/"

stages:
  - Lint
  - Unit Tests
  - name: e2e Tests
    if: 1 = 2

jobs:
  include:
  - stage: Lint
    script:
    - npm run lint
  - stage: Unit Tests
    env:
    - CI_ENV=true
    script:
    - npm test
  - stage: e2e Tests
    script:
    - npm run e2e

notifications:
  email: false
