sudo: required
language: node_js
node_js:
- '8.4'
branches:
  only:
  - master
addons:
  chrome: stable
install:
- npm install
cache:
  directories:
  - "/home/travis/.npm/"
  - "$HOME/.npm"
  - "$HOME/.cache"
  - node_modules
stages:
- Lint
- Unit Tests
jobs:
  include:
  - stage: Lint
    script:
    - npm run lint
  - stage: Unit Tests
    env:
    - CI_ENV=true
    script:
    - npm test
notifications:
  slack:
    rooms:
      secure: ElJe0CHQ9eCQRdaW2F/uhm384dwdQD6ZDLpcIU+GB3HyQadjCRzLm+YUTgtv1x2dtjRwshRjMhANNee8+lvAB2Ye87SCxhay45GcdwVALjIHI0L12A0tn51GbPkG9p8zNde+GbJyuFYuVJtuxsRtLMG9hM1sslqKBtGVAp4QLaYf8tVWnHocexqnwEV42FBAFlmKNrYuVFQblspZYcgrNhJjbTKMH4W8NtbqpuXvUsYJbw50dHtxi0kkMgWg7MSrnolD7bLCJ/idJUYyICwLYnfBt+kGqwREEFB+6WGJMnJ93ynT9uO6pik1TPiEcrf7uJzpSTnsxAfNtLuquaNO4Z9UPKq/teTJ/w6bXdEbsz11oPxtXXP+RxotFz0vT6w6+chjvlHUNhdba/qVlT4u7ea+OETtyGtr+9sI3r01zf5jzJdt1lRt/8KnbmaqMT8urj8nYSadV/4FYptXnYGeFivOx1B6gt/Cfi+5fuO/5FxQ+0ARPi4wsoE9BAPUP+LWhU8hM/zI/gPRqkHIu9a1F6oDvYaBxQP15Me6bECFSAA4id84NsYDBb33/J8d9qK5f/QLL86ulZyWb74p7XfSDq71VwtIqKcz8EMZEXRV9Kuf1Y1KqslQ9hEKAfdfFTh1Q7RjSoGBvzZMfVjOo8mZJp+b5i4yUoOmmRycXKTOyqU=
    on_success: always
