version: '2'
services:

  ##############################################################################
  # These two "services" are not meant to be instantiated, but instead extended.
  # Unfortunately, this is necessary for those working at the HPE office where
  # the proxy is a sad, Sad, SAD way of life.
  ##############################################################################

  imageCommon:
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}


  buildCommon:
    extends: imageCommon
    build:
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - no_proxy=${no_proxy}

  ##############################################################################


  postgres:
    extends: imageCommon
    image: postgres:latest
    env_file:
      ./postgres.env
    ports:
      - "5432:5432"


  goose:
    extends: buildCommon
    build:
      context: $GOPATH/src/github.com/hpcloud/portal-proxy
      dockerfile: db/Dockerfile.goose.dev
    # volumes:
    #   - $GOPATH/src/github.com/hpcloud/portal-proxy:/goose


  proxy:
    extends: buildCommon
    build:
      context: $GOPATH/src/github.com/hpcloud/portal-proxy
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3003"
    env_file:
      ./proxy.env
    environment:
      - GITHUB_OAUTH_CLIENT_ID=${GITHUB_OAUTH_CLIENT_ID}
      - GITHUB_OAUTH_CLIENT_SECRET=${GITHUB_OAUTH_CLIENT_SECRET}
      - GITHUB_OAUTH_STATE=${GITHUB_OAUTH_STATE}
    volumes:
      - $GOPATH/src/github.com/hpcloud/portal-proxy:/srv


  nginx:
    extends: buildCommon
    build:
      context: ../stratos-ui/containers/nginx
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    volumes:
      - ../stratos-ui/dist:/usr/share/nginx/html:ro
    # NOTE: links field must be included individually if extending this file.
    #links:
    #  - proxy:proxy


  ui:
    extends: buildCommon
    build:
      context: ../stratos-ui
      dockerfile: Dockerfile.dev

    volumes:
      - ../stratos-ui:/usr/src/app
      - ../helion-ui-framework:/usr/src/helion-ui-framework
