data:
  image: ubuntu:14.04
  volumes:
    - /var/lib/mysql


db:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=stratos
    - MYSQL_DATABASE=stratos-db
    - MYSQL_USER=stratos
    - MYSQL_PASSWORD=stratos
  volumes:
    - ../stratos-identity-db/versions:/docker-entrypoint-initdb.d
  volumes_from:
    - data


cf:
  build: ../stratos-node-server
  dockerfile: Dockerfile.demo.mock_api
  ports:
    - "3002:3002"
  environment:
    - PORT=3002
  volumes:
    - ../stratos-node-server:/usr/src/app
    - /usr/src/app/node_modules


auth:
  build: ../stratos-node-server
  dockerfile: Dockerfile.demo.mock_auth
  ports:
    - "3001:3001"
  environment:
    - PORT=3001
  volumes:
    - ../stratos-node-server:/usr/src/app
    - /usr/src/app/node_modules


api:
  build: ../stratos-node-server
  dockerfile: Dockerfile.prod
  ports:
    - "3000:3000"
  environment:
    - PORT=3000
    - MYSQL_ROOT_PASSWORD=stratos
    - MYSQL_DATABASE=stratos-db
    - MYSQL_USER=stratos
    - MYSQL_PASSWORD=stratos
  volumes:
    - ../stratos-node-server:/usr/src/app
    - /usr/src/app/node_modules
  links:
    - db:db
    - auth:auth_service
    - cf:cf_service


nginx:
  build: ../stratos-server
  dockerfile: Dockerfile.prod
  ports:
    - "80:80"
  volumes:
    - ../stratos-ui/dist:/usr/share/nginx/html:ro
  links:
    - api:api


ui:
  build: ../stratos-ui
  dockerfile: Dockerfile.prod
  volumes:
    - ../stratos-ui:/usr/src/app
    - ../helion-ui-framework:/usr/src/helion-ui-framework
    - ../helion-ui-theme:/usr/src/helion-ui-theme
