version: '2'
services:

  # The development docker-compose file.
  # Use this to have things like "gulp watch" running in the UI.

  ui:
    extends:
      file: common.yml
      service: ui
    build:
      context: ../stratos-ui
      dockerfile: Dockerfile.test


  postgres:
    extends:
      file: common.yml
      service: postgres


  goose:
    extends:
      file: common.yml
      service: goose
    links:
      - postgres:postgres


  proxy:
    extends:
      file: common.yml
      service: proxy
    environment:
      CONSOLE_CLIENT: console
      HCP_IDENTITY_SCHEME: https
      HCP_IDENTITY_HOST: ident.helion.space
      HCP_IDENTITY_PORT: 443
    links:
      - postgres:postgres


  nginx:
    extends:
      file: common.yml
      service: nginx
    links:
      - proxy:proxy
