version: '2'
services:

  # The development docker-compose file.
  # Use this to have things like "gulp watch" running in the UI.


  postgres:
    extends:
      file: common.yml
      service: postgres


  proxy:
    extends:
      file: common.yml
      service: proxy
    environment:
      CONSOLE_CLIENT: console
      UAA_ENDPOINT: http://ident.helion.space:8080/oauth/token
    links:
      - postgres:postgres


  nginx:
    extends:
      file: common.yml
      service: nginx
    links:
      - proxy:proxy


  ui:
    extends:
      file: common.yml
      service: ui
    build:
      context: ../stratos-ui
      dockerfile: Dockerfile.test
