# The development docker-compose file.
# Use this to have things like "gulp watch" running in the UI.
data:
  extends:
    file: common.yml
    service: data


db:
  extends:
    file: common.yml
    service: db
  volumes_from:
    - data


# Mock Cloud Foundry service
cf:
  extends:
    file: common.yml
    service: cf


# Mock Auth service
auth:
  extends:
    file: common.yml
    service: auth


api:
  extends:
    file: common.yml
    service: api
  links:
    - db:db
    - auth:auth_service
    - cf:cf_service


nginx:
  extends:
    file: common.yml
    service: nginx
  links:
    - api:api


ui:
  extends:
    file: common.yml
    service: ui
  dockerfile: Dockerfile
