# The development docker-compose file.

postgres:
  extends:
    file: common.yml
    service: postgres


proxy:
  extends:
    file: common.yml
    service: proxy
  links:
    - postgres:postgres


nginx:
  extends:
    file: common.yml
    service: nginx
  links:
    - proxy:proxy


ui:
  extends:
    file: common.yml
    service: ui
  dockerfile: Dockerfile
