---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: mysql
  spec:
    ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
    - name: galera-tcp
      port: 4567
      protocol: TCP
      targetPort: galera-tcp
    - name: galera-udp
      port: 4567
      protocol: UDP
      targetPort: galera-udp
    - name: galera-ist
      port: 4568
      protocol: TCP
      targetPort: galera-ist
    - name: healthcheck
      port: 9200
      protocol: TCP
      targetPort: healthcheck
    - name: xtrabackup
      port: 4444
      protocol: TCP
      targetPort: xtrabackup
    selector:
      skiff-role-name: mysql
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: mysql-pod
  spec:
    clusterIP: None
    ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 0
    - name: galera-tcp
      port: 4567
      protocol: TCP
      targetPort: 0
    - name: galera-udp
      port: 4567
      protocol: UDP
      targetPort: 0
    - name: galera-ist
      port: 4568
      protocol: TCP
      targetPort: 0
    - name: healthcheck
      port: 9200
      protocol: TCP
      targetPort: 0
    - name: xtrabackup
      port: 4444
      protocol: TCP
      targetPort: 0
    selector:
      skiff-role-name: mysql
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: uaa
spec:
  ports:
  - name: uaa
    port: 8080
    protocol: TCP
    targetPort: uaa
  - name: uaa-ssl
    port: 8443
    protocol: TCP
    targetPort: uaa-ssl
  selector:
    skiff-role-name: uaa
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: uaa-ports
spec:
  ports:
  - name: uaa-ssl
    port: 8443
    targetPort: 8443
  externalIPs :
  - 192.168.77.77
  selector:
    skiff-role-name: uaa

