apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hsc-encryption-key-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hsc-upgrade-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: postgres-volume
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 2Gi
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: console-secret
data:
  stolon: Y2hhbmczbTM=
  pgsql-password: Y2hhbmczbTM=
  console-cert-key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRW93SUJBQUtDQVFFQXJnek1UQWxoZXIxTWM1RjRjdDM4b1A3RWczVUU1LzF2SzFXcjJ6OHBpYWtpNkMwQQ0KcUNHZFRGYkJaZzEzbVZwM2ZQZWlrY0hvSlJ0bnBmd2cvZ3JQaVhSeU1GYlpjTjhhUTlXekhZNUh6UjRTSG1VOA0KT28vUVBXNzZBeEk4ejc4ZDVDQldxNHdVM011UW1TTTJZMkhWQ1AvSVBOWGNtNzVMWDJKTzB4OVkrSTV4Yjh6Tw0KUUkrRCtOd1BrRjd5VkZhenF5K1g5VUphaG5NOG5yZFphMDBZOVM2V3RiYUpRRU5hcGY1V0hpd0tvRXRBbmJRaw0KRkhwREtEbTRWSDRjWlZBdFNuVzdKK2M0cit0OGtYRkFjUkxjTnZ0blQ3ZEJRVmp3c2g2dWgyZ0ZNdUE2dlF1Zw0KMTJDTi9YQTVwNlkwT2tTTzBhTU1yaVE1OUVVMUFxWE00VW1yK1FJREFRQUJBb0lCQUdqbTljdHVhLzVhVWRYbA0KKzc3ZjVQLzBEZVZkaGxOOUFLQVJ4cjhpVnByT0FtZ0ZsN3UrWnR3My9lRFFoU0U4MFgvVWtYdGdiOWJOcWE3MQ0KUTcxYUxyUWVKeVRUYzhMLzlRaWxxSXRMMGlMaTJQRFErM2dnYmRaWktQN280eFlqanBTTW1UQlVBYzhDTW1qYQ0KUEZHeUNZQ2ZDY1VBOFRJOWc1ZzkzRnlMTEVqQ011TzIrdm1kZFltVDFwcE4rdGoyVXlJOGthcGQ0ZHdPdzdNOA0KdUFzM2l4bXQyUGJVU25TMlRkVm4rV0RDN1plSHdndVZ3VmRYK0o0c1B5WVFKdnpMN0x6bW8xVzNkaVA4Z1RkRQ0KMzE2cEQrOEs3b0lOOHhLZ29EVUIwaUxhS3hKNUttQVdIQ01SNVhGSDU5SHQwelBqVUpiNmJDLzVPaWM4ZHZ4dQ0KOHZJK3pIRUNnWUVBeHpFYnM3eU1vaTN0RzQyblZoNFBZZWE1eEVZVWdBTENIeDBOVzlCZkZLQTZmVTR6UkZuYQ0KWlRsRExYK2JsWmNIbHdabytHcGpyVnZoK0ZJdGMyUktuNjJoRFRmU3picitFZ0hURFhBTEw2NCsxaTJ5TGhQeg0KZWNoTW9QU2pmUk5OQnRybFd1SWlnZnF0elY4bVMwNzByYXZiaXJ2NGFjbnRWdHNacHM1dlRqOENnWUVBMzdBWQ0KOEJtZHUxcUVqMGdqVjlUTDY1amJvWnNkNktnSWlHRGVEUUVtcFYwM2xwejF4SENiTHRrdmc0RWMwaFpzeXpGYw0KajBIcXVNN0dKdW1kTG1DSWJ3cjF6eEVDMTV1blhKYmptMU5QWTVWS2l2dUZCMW9yVEduTFhzTlk3emdZL2I3eA0KQmhseDhZd3pOaDJ3T1pWdmJRdDVDbmp3N1FRUDkwdUVlcTZYNThjQ2dZQkFpbzN5VUE2MVlmSW84bDRkRGtKbg0KczIzUHhmRlFoUlJISm8rMGh6QzNxeThvZU5VdHVYdUZQdWVnYjIrSEtkZWd2TWY0YmVoOFBJQmNpS3dIYnFDcg0KV29RTGwySHJuVUpEcldtb09meTE1MXllNDFHUGtwRmFqV2NlNUFXeE9qYkVHTnNsOW8yOTFlN0kwNkxCMWdSNw0KM1dxV2FrK1VYNFJTbDAyWmVkd2cyd0tCZ0g2M2ZZa1dtZG8yenYxME9rRlpWU1BqOWhlNGpkcnN4ZGlzTjE1YQ0KbG8vN0hMQi92bUpJQUVFcjI5UzlZWnhLQTl1ZjNQVnl2QXR4WjZOSG1EbGJpaTZOb081cWpwZWhuOCs5MHJaOQ0KSFc0bWRwSUJKajBpQVlGS05XRTdmTGdYcVdDbHVGaGlOY0JHVWdTSUVQcXVBdTlkSG5hbVNLV2NOWWM4Q3BLTg0KTVpTbEFvR0JBTWJZV01vS1RqU2RpeENtTEo1TWVIVHdYdnk2MkxSeHZwc0tJVTJqOUFyTHl0UEU1N2ZEd091cg0KNGV5U2EvOUxrbEdqVTBYMXo1YlplUWd1K2RvNGNoOGlYRk55eC9BYWxnWlJuRlFudDliVm9iMk1YaVIzRENORg0KSkFaYTVWb0lKSHdqdE9jSXJUMFVJMExON3FRNTRHYWR4ZmJrTE5pemdUWHdad0V4L2JsNQ0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0=
  console-cert: DQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0NCk1JSUZmekNDQkdlZ0F3SUJBZ0lVWEdWelNMM3ZyUlluNHBIK09HUTFRMHA2Z24wd0RRWUpLb1pJaHZjTkFRRUwNCkJRQXdnWWd4Q3pBSkJnTlZCQVlUQWxWVE1STXdFUVlEVlFRSUV3cFhZWE5vYVc1bmRHOXVNUkF3RGdZRFZRUUgNCkV3ZFRaV0YwZEd4bE1TTXdJUVlEVlFRS0V4cElaWGRzWlhSMElGQmhZMnRoY21RZ1JXNTBaWEp3Y21selpURVMNCk1CQUdBMVVFQ3hNSlNGQkZJRU5zYjNWa01Sa3dGd1lEVlFRREV4QklRMUFnUW05dmRITjBjbUZ3SUVOQk1CNFgNCkRURTNNRFF3TlRFeU1qa3dNRm9YRFRFNE1EUXdOVEV5TWprd01Gb3dnWUV4Q3pBSkJnTlZCQVlUQWxWVE1STXcNCkVRWURWUVFJRXdwWFlYTm9hVzVuZEc5dU1SQXdEZ1lEVlFRSEV3ZFRaV0YwZEd4bE1TTXdJUVlEVlFRS0V4cEkNClpYZHNaWFIwSUZCaFkydGhjbVFnUlc1MFpYSndjbWx6WlRFU01CQUdBMVVFQ3hNSlNGQkZJRU5zYjNWa01SSXcNCkVBWURWUVFERXdrcUxtaHpZeTV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUINCkFRQ3VETXhNQ1dGNnZVeHprWGh5M2Z5Zy9zU0RkUVRuL1c4clZhdmJQeW1KcVNMb0xRQ29JWjFNVnNGbURYZVoNClduZDg5NktSd2VnbEcyZWwvQ0QrQ3MrSmRISXdWdGx3M3hwRDFiTWRqa2ZOSGhJZVpUdzZqOUE5YnZvREVqelANCnZ4M2tJRmFyakJUY3k1Q1pJelpqWWRVSS84ZzgxZHlidmt0ZllrN1RIMWo0am5GdnpNNUFqNFA0M0ErUVh2SlUNClZyT3JMNWYxUWxxR2N6eWV0MWxyVFJqMUxwYTF0b2xBUTFxbC9sWWVMQXFnUzBDZHRDUVVla01vT2JoVWZoeGwNClVDMUtkYnNuNXppdjYzeVJjVUJ4RXR3MisyZFB0MEZCV1BDeUhxNkhhQVV5NERxOUM2RFhZSTM5Y0RtbnBqUTYNClJJN1Jvd3l1SkRuMFJUVUNwY3poU2F2NUFnTUJBQUdqZ2dIa01JSUI0REFPQmdOVkhROEJBZjhFQkFNQ0JhQXcNCkhRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWUQNClZSME9CQllFRkpmUDhWa1oyVElCOEV2SU55WmdraldaUVVCSE1COEdBMVVkSXdRWU1CYUFGTU1KWXg0U2dSMlINCmFSeWZoKzByVHg0ZExjUVlNSUlCWHdZRFZSMFJCSUlCVmpDQ0FWS0NDU291YUhOakxuTjJZNElWS2k1b2MyTXUNCmMzWmpMbU5zZFhOMFpYSXVhR053Z2d0b2MyTXRZMjl1YzI5c1pZSVRhSE5qTFdOdmJuTnZiR1V1YUhOakxuTjINClk0SWZhSE5qTFdOdmJuTnZiR1V1YUhOakxuTjJZeTVqYkhWemRHVnlMbWhqY0lJTktpNW9jMk10WTI5dWMyOXMNClpZSVZLaTVvYzJNdFkyOXVjMjlzWlM1b2MyTXVjM1pqZ2lFcUxtaHpZeTFqYjI1emIyeGxMbWh6WXk1emRtTXUNClkyeDFjM1JsY2k1b1kzQ0NEMmh6WXkxamIyNXpiMnhsTFdsdWRJSVhhSE5qTFdOdmJuTnZiR1V0YVc1MExtaHoNCll5NXpkbU9DSTJoell5MWpiMjV6YjJ4bExXbHVkQzVvYzJNdWMzWmpMbU5zZFhOMFpYSXVhR053Z2hFcUxtaHoNCll5MWpiMjV6YjJ4bExXbHVkSUlaS2k1b2MyTXRZMjl1YzI5c1pTMXBiblF1YUhOakxuTjJZNElsS2k1b2MyTXQNClkyOXVjMjlzWlMxcGJuUXVhSE5qTG5OMll5NWpiSFZ6ZEdWeUxtaGpjREFOQmdrcWhraUc5dzBCQVFzRkFBT0MNCkFRRUF4dDBBSWlOMjZtZFRZQjhMakcwTy9RMjJaTUNxblBzdTdIR1VPVmswZzU5S1c5UFU2MCs4anlyZS9MZmMNCkNIMDlET25UVlBybG1naEFxbjZvMnFBUyt2WktISUsrNTBPdklLTy82U3dmdm1KbGsxSDB4QVBxbS9TV3R0SHENClFJeklReHF6R0ErNnJxb1JXNUttcWR5N3htdmg1Zlk2c3BWSjBVeUlUZTl6TlplRG1CMkVXSjdHcS9FL3huY3oNCm1sQkZSMzlXWHA2UHRyK1R1OFpoVWZTekNwR0p3RWxockFENjhFb0o3UzFyN24yd2habFVBQ1JOQVc1a3dYWWENCmdIYkttcklETWRLOXQwU2tzUDFNQmZOTjA5L2V0VlVQRUZlYmZ6NnVOaW1mcGpFcStGSG12ZS9FeXJTdi9haG0NCklXRVUwSHZ6MVA5d2h0V1ZaU3M3dDQ0L3JnPT0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: preflight-job
  name: preflight-job
spec:
 template:
     metadata:
       labels:
         app: console
         job: preflight
     spec:
       containers:
         - env:
           - name: UPGRADE_VOLUME
             value: hsc-upgrade-volume
           - name: UPGRADE_LOCK_FILENAME
             value: upgrade.lock
           - name: ENCRYPTION_KEY_VOLUME
             value: hsc-encryption-key-volume
           - name: ENCRYPTION_KEY_FILENAME
             value: key
           image: {{.Values.dockerRegistry}}/{{.Values.dockerOrg}}/{{.Values.images.preflight}}:{{.Values.consoleVersion}}
           name: preflight-job
           volumeMounts:
           - mountPath: /hsc-upgrade-volume
             name: hsc-upgrade-volume
           - mountPath: /hsc-encryption-key-volume
             name: hsc-encryption-key-volume
       restartPolicy: Never
       volumes:
       - name: hsc-upgrade-volume
         persistentVolumeClaim:
           claimName: hsc-upgrade-volume
       - name: hsc-encryption-key-volume
         persistentVolumeClaim:
           claimName: hsc-encryption-key-volume
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: console
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
      - image: {{.Values.dockerRegistry}}/{{.Values.dockerOrg}}/{{.Values.images.console}}:{{.Values.consoleVersion}}
        name: ui
        env:
        - name: UAA_ENDPOINT
          value: http://console-uaa-int:8080
        volumeMounts:
        - mountPath: /etc/secrets/
          name: console-secret
          readOnly: true
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
      - image: {{.Values.dockerRegistry}}/{{.Values.dockerOrg}}/{{.Values.images.proxy}}:{{.Values.consoleVersion}}
        name: proxy
        env:
        - name: PGSQL_USER
          value: console
        - name: PGSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: console-secret
              key: pgsql-password
        - name: PGSQL_DATABASE
          value: console-db
        - name: PGSQL_HOST
          value: console-postgres-int
        - name: PGSQL_PORT
          value: "5432"
        - name: PGSQL_CONNECT_TIMEOUT_IN_SECS
          value: "100"
        - name: PGSQL_SSL_MODE
          value: disable
        - name: HTTP_CONNECTION_TIMEOUT_IN_SECS
          value: "10"
        - name: HTTP_CLIENT_TIMEOUT_IN_SECS
          value: "20"
        - name: SKIP_TLS_VERIFICATION
          value: "false"
        - name: CONSOLE_PROXY_TLS_ADDRESS
          value: :3003
        - name: CONSOLE_CLIENT
          value: console
        - name: HCE_CLIENT
          value: hce
        - name: HSM_CLIENT
          value: hsm
        - name: HCP_CLIENT
          value: hcp
        - name: HCF_CLIENT
          value: cf
        - name: ALLOWED_ORIGINS
          value: https://localhost
        - name: ENCRYPTION_KEY_VOLUME
          value: hsc-encryption-key-volume
        - name: ENCRYPTION_KEY_FILENAME
          value: key
        - name: HTTP_PROXY
        - name: HTTPS_PROXY
        - name: NO_PROXY
        - name: FTP_PROXY
        - name: SOCKS_PROXY
        - name: UAA_ENDPOINT
          value: http://console-uaa-int:8080
        ports:
        - containerPort: 3003
          name: proxy
          protocol: TCP
        volumeMounts:
        - mountPath: /hsc-upgrade-volume
          name: hsc-upgrade-volume
        - mountPath: /hsc-encryption-key-volume
          name: hsc-encryption-key-volume
        - mountPath: /etc/secrets/
          name: console-secret
          readOnly: true
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres-volume
      - name: hsc-upgrade-volume
        persistentVolumeClaim:
          claimName: hsc-upgrade-volume
      - name: hsc-encryption-key-volume
        persistentVolumeClaim:
          claimName: hsc-encryption-key-volume
      - name: console-secret
        secret:
          secretName: console-secret
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: console-postgres
    spec:
      containers:
      - image: {{.Values.dockerRegistry}}/{{.Values.dockerOrg}}/{{.Values.images.postgres}}:{{.Values.consoleVersion}}
        name: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD_FILE
          value: /etc/secrets/stolon
        - name: PGDATA
          value: /stolon-data/postgres
        - name: HTTP_PROXY
        - name: HTTPS_PROXY
        - name: FTP_PROXY
        - name: SOCKS_PROXY
        volumeMounts:
        - mountPath: /stolon-data
          name: postgres-volume
        - mountPath: /etc/secrets/
          name: console-secret
          readOnly: true
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres-volume
      - name: hsc-encryption-key-volume
        persistentVolumeClaim:
          claimName: hsc-encryption-key-volume
      - name: console-secret
        secret:
          secretName: console-secret
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: uaa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: console-uaa
    spec:
      containers:
      - image: susetest/uaa:latest
        name: console-identity
        ports:
        - containerPort: 8080
          name: uaa
          protocol: TCP
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres-volume
      - name: hsc-encryption-key-volume
        persistentVolumeClaim:
          claimName: hsc-encryption-key-volume
      - name: console-secret
        secret:
          secretName: console-secret

