---
platform: linux
image_resource:
  type: docker-image
  source: {repository: busybox}
inputs:
- name: stratos-deploy
- name: resource-version
outputs:
- name: stratos-deploy-output
run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    find .
    pwd
    ls -la
    VERSION_TAG=`cat resource-version/number`
    sh $PWD/stratos-deploy/ci/scripts/build-hsm-configs.sh $PWD/stratos-deploy $PWD/stratos-deploy-output $registry $VERSION_TAG
    cd -
    ls -la ./stratos-deploy-output
