resources:
- name: stratos
  type: git
  source:
    uri: git@github.com:((github-organization))/((github-repository))
    branch: ((stratos-branch))
    private_key: ((github-private-key))
- name: aio-docker-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: splatform/stratos
- name: after-midnight
  type: time
  source:
    start: 12:00 AM
    stop: 2:00 AM
    location: UTC
groups:
- name: tests
  jobs:
  - build-helm-images
  - build-dc-images
  - build-aio-image

jobs:
- name: build-helm-images
  plan:
  - get: stratos
  - get: after-midnight
    trigger: true
  - do:
    - task: generete-certs
      timeout: 2m
      file: stratos/deploy/ci/tasks/build-images/generate-certs.yml
    - task: build
      privileged: true
      timeout: 30m
      file: stratos/deploy/ci/tasks/build-images/build-helm.yml
      params:
        DOCKER_USERNAME: ((docker-username))
        DOCKER_PASSWORD: ((docker-password))
- name: build-dc-images
  plan:
  - get: stratos
  - get: after-midnight
    trigger: true
  - do:
    - task: generete-certs
      timeout: 2m
      file: stratos/deploy/ci/tasks/build-images/generate-certs.yml
    - task: build
      privileged: true
      timeout: 30m
      file: stratos/deploy/ci/tasks/build-images/build-dc.yml
      params:
        DOCKER_USERNAME: ((docker-username))
        DOCKER_PASSWORD: ((docker-password))

- name: build-aio-image
  public: true
  serial: true
  plan:
  - get: stratos
  - get: after-midnight
    trigger: true
  - put: aio-docker-image
    params:
      build: stratos
      dockerfile: stratos/deploy/Dockerfile.all-in-one
