---
resource_types:
- name: docker-image
  type: docker-image
  privileged: true
  source:
    repository: ((docker-image-resource))
    tag: ((docker-image-resource-tag))

resources:
- name: stratos
  type: git
  source:
    uri: git@github.com:((github-organization))/((github-repository))
    branch: ((stratos-branch))
    private_key: ((github-private-key))
- name: aio-docker-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: splatform/stratos
- name: after-midnight
  type: time
  source:
    start: 12:00 AM
    stop: 2:00 AM
    location: UTC
    # Docker Images
- name: jetstream-dc-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-org))/stratos-dc-jetstream
- name: postflight-dc-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-org))/stratos-dc-postflight-job
- name: mariadb-dc-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-org))/stratos-dc-mariadb
- name: ui-dc-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-org))/stratos-dc-console

groups:
- name: tests
  jobs:
  # - build-helm-images
  - build-dc-images
  - build-aio-image

jobs:
# - name: build-helm-images
#   plan:
#   - get: stratos
#   - get: after-midnight
#     trigger: true
#   - do:
#     - task: generete-certs
#       timeout: 2m
#       file: stratos/deploy/ci/tasks/build-images/generate-certs.yml
#     - task: build
#       privileged: true
#       timeout: 30m
#       file: stratos/deploy/ci/tasks/build-images/build-helm.yml
#       params:
#         DOCKER_USERNAME: ((docker-username))
#         DOCKER_PASSWORD: ((docker-password))
- name: build-dc-images
  plan:
  - get: stratos
    trigger: true
  - aggregate:
    - do:
      - put: jetstream-dc-image
        params:
          dockerfile: stratos/deploy/Dockerfile.bk
          build: stratos/
          target_name:  dev-build
          tag_as_latest: true
      - put: postflight-dc-image
        params:
          dockerfile: stratos/deploy/Dockerfile.bk
          build: stratos/
          target_name:  postflight-job
          tag_as_latest: true
      - put: mariadb-dc-image
        params:
          dockerfile: stratos/deploy/db/Dockerfile.mariadb
          build: stratos/deploy/db
          tag_as_latest: true
      - put: ui-dc-image
        params:
          dockerfile: stratos/deploy/Dockerfile.ui
          build: stratos/
          target_name: prod-build
          tag_as_latest: true

- name: build-aio-image
  public: true
  serial: true
  plan:
  - get: stratos
  - get: after-midnight
    trigger: true
  - put: aio-docker-image
    params:
      build: stratos
      dockerfile: stratos/deploy/Dockerfile.all-in-one
