resources:
- name: stratos
  type: git
  source:
    branch: {{stratos-branch}}
    uri: git@github.com:((github-organization))((github-repository))
    private_key: {{github-private-key}}
    tag_filter: "[0-9]*"
- name: helm-chart-values-sle
  type: s3
  source:
    bucket: concourse-stratos-ui
    endpoint: {{minio-server-endpoint}}
    regexp: temp-artifacts/values.yaml-(?P<version>.*)
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-access-key}}
    region_name: eu-central-1
- name: helm-chart-Chart-sle
  type: s3
  source:
    bucket: concourse-stratos-ui
    endpoint: {{minio-server-endpoint}}
    regexp: temp-artifacts/Chart.yaml-(?P<version>.*)
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-access-key}}
    region_name: eu-central-1
- name: helm-chart-tarball-sle
  type: s3
  source:
    bucket: concourse-stratos-ui
    endpoint: {{minio-server-endpoint}}
    regexp: temp-artifacts/console-(?P<version>.*).tgz
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-access-key}}
    region_name: eu-central-1

groups:
- name: tests
  jobs:
  - build-sle-helm-images
  - create-sle-chart

jobs:
- name: build-sle-helm-images
  plan:
  - get: stratos
    trigger: true
  - do:
    - task: generete-certs
      timeout: 2m
      file: stratos/deploy/ci/tasks/build-images/generate-certs.yml
    - task: build
      privileged: true
      timeout: 50m
      file: stratos/deploy/ci/tasks/release/build-helm.yml
      params:
        DOCKER_USERNAME: {{staging-repository-username}}
        DOCKER_PASSWORD: {{staging-repository-password}}
        BASE_IMAGE: {{staging-repo-base-image-tag}}
        STAGING_REPOSITORY: {{staging-repository}}
        IS_OFFICIAL: "true"
    - put: helm-chart-values-sle
      params:
        file: helm-build/values.yaml-*
        acl: public-read
    - put: helm-chart-Chart-sle
      params:
        file: helm-build/Chart.yaml-*
        acl: public-read

- name: create-sle-chart
  plan:
  - get: stratos
    passed: [build-sle-helm-images]
    trigger: true
  - get: helm-chart-Chart-sle
    passed: [build-sle-helm-images]
  - get: helm-chart-values-sle
    passed: [build-sle-helm-images]
  - do:
    - task: build
      privileged: true
      timeout: 30m
      file: stratos/deploy/ci/tasks/release/create-chart-sle.yml
      params:
        GIT_USER: {{concourse-user}}
        GIT_EMAIL: {{concourse-email}}
        GITHUB_ORG: {{github-organization}}
        GITHUB_REPO: {{github-repository}}
        GIT_PRIVATE_KEY: {{github-private-key}}
        BASE_IMAGE: "sle"
    - put: helm-chart-tarball-sle
      params:
        file: helm-chart/*.tgz
        acl: public-read