resource_types:
- name: ftp
  type: ftp
  source:
    repository: aequitas/ftp-resource
    tag: latest

resources:
- name: stratos-ui
  type: git
  source:
    branch: {{stratos-ui-branch}}
    private_key: {{github-private-key}}
    uri: git@github.com:irfanhabib/stratos-ui.git
    tag_filter: release-*
- name: upload-helm-chart-values
  type: ftp
  source: ftp://concourse@10.4.21.241:concourse-build/
  regex: values.yaml-release-*
- name: helm-chart-values
  type: ftp
  source: ftp://concourse@10.4.21.241:concourse-build/
  regex: (?P<file>values\.yaml-(?P<version>release-.*))
- name: helm-chart-Chart
  type: ftp
  source: ftp://concourse@10.4.21.241:concourse-build/
  regex: (?P<file>Chart\.yaml-(?P<version>release-.*))
- name: helm-chart-tarball
  type: ftp
  source: ftp://concourse@10.4.21.241:concourse-build/
  regex: (?P<file>console-(?P<version>release-.*)\.tgz)
- name: helm-chart-repo
  type: ftp
  source: ftp://concourse@10.4.21.241:concourse-build/
  regex: (?P<file>index.yaml-(?P<version>release-.*))




groups:
- name: tests
  jobs:
  - build-helm-images
  - update-repo
  - update-github-release

jobs:
- name: build-helm-images
  plan:
  - get: stratos-ui
    trigger: true
  - do:
    - task: generete-certs
      timeout: 2m
      file: stratos-ui/deploy/ci/tasks/build-images/generate-certs.yml
    - task: build
      privileged: true
      timeout: 30m
      file: stratos-ui/deploy/ci/tasks/release/build-helm.yml
      params:
        DOCKER_USERNAME: {{docker-username}}
        DOCKER_PASSWORD: {{docker-password}}
      put: helm-chart-values
      params:
        file: helm-build/values.yaml-*
      put: helm-chart-Chart
      params:
        file: helm-build/Chart.yaml-*

- name: update-repo
  plan:
  - get: stratos-ui
    passed: [build-helm-images]
    trigger: true
  - get: helm-chart-Chart
    params:
      version: release-*
  - get: helm-chart-values
    params:
      version: release-*

  - do:
    - task: build
      privileged: true
      timeout: 30m
      file: stratos-ui/deploy/ci/tasks/release/create-chart.yml
      params:
        GIT_USER: {{concourse-user}}
        GIT_EMAIL: {{concourse-email}}
        GIT_PRIVATE_KEY: {{github-private-key}}
      put: helm-chart-tarball
      params:
        file: helm-chart/*.tgz
      put: helm-chart-repo
      params:
        file: helm-chart/index*



- name: update-github-release
  plan:
  - get: stratos-ui
    passed: [update-repo]
    trigger: true
  - get: helm-chart-tarball
    params:
      version: release*
  - get: helm-chart-repo
    params:
      version: release*
  - do:
    - task: build
      privileged: true
      timeout: 30m
      file: stratos-ui/deploy/ci/tasks/release/upgrade-gh-release.yml
      params:
        GITHUB_TOKEN: {{github-access-token}}
        GITHUB_USER: {{github-organization}}
        GITHUB_REPO: {{github-repository}}
