# Nightly AIO image build
---
resource_types:
- name: docker-image
  type: docker-image
  privileged: true
  source:
    repository: ((docker-resource-image))
    tag: ((docker-resource-image-tag))

resources:
- name: stratos
  type: git
  source:
    uri: git@github.com:((stratos-repository-organization))/((stratos-repository))
    branch: ((stratos-repository-branch))
    private_key: ((github-private-key))
- name: aio-docker-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-organization))/((aio-docker-image-name))
- name: after-midnight
  type: time
  source:
    start: 12:00 AM
    stop: 2:00 AM
    location: UTC

groups:
- name: build
  jobs:
  - build-aio-image

jobs:
- name: build-aio-image
  public: true
  serial: true
  plan:
  - get: stratos
  - get: after-midnight
    trigger: true
  - put: aio-docker-image
    params:
      build: stratos
      dockerfile: stratos/deploy/Dockerfile.all-in-one
      tag_as_latest: false
      tag: nightly

