---
platform: linux
inputs:
- name: stratos-ui
- name: portal-proxy-output
# Parameterised task files are currently not supported in Concourse
# Once that is implemented we can refactor the following into a variable
image_resource:
  type: docker-image
  source:
   repository:  ci-registry.ngrok.io:80/concourse-dcind
   tag: "latest"
   insecure_registries: [ "ci-registry.ngrok.io:80" ]

run:
  path: sh
  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      cd stratos-ui/deploy/ci/scripts
      docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

      ./build_concourse_image.sh
      docker tag docker.io/splatform/concourse:test ci-registry.ngrok.io:80/splatform/stratos-concourse:latest
      docker push ci-registry.ngrok.io:80/splatform/stratos-concourse:latest


