apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: uaa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: console-uaa
    spec:
      containers:
      - image: susetest/uaa:latest
        name: console-identity
        ports:
        - containerPort: 8080
          name: uaa
          protocol: TCP
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres-volume
      - name: hsc-encryption-key-volume
        persistentVolumeClaim:
          claimName: hsc-encryption-key-volume
      - name: console-secret
        secret:
          secretName: console-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: console-uaa
  name: console-uaa-int
spec:
  ports:
  - name: uaa
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
        app: console-uaa
  type: ClusterIP
