apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: console-postgres
    spec:
      containers:
      - image: stackatodev/hsc-postgres:1.0.37-0-g1ae4b40
        name: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD_FILE
          value: /etc/secrets/stolon
        - name: PGDATA
          value: /stolon-data/postgres
        - name: HTTP_PROXY
        - name: HTTPS_PROXY
        - name: FTP_PROXY
        - name: SOCKS_PROXY
        volumeMounts:
        - mountPath: /stolon-data
          name: postgres-volume
        - mountPath: /etc/secrets/
          name: console-secret
          readOnly: true
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres-volume
      - name: hsc-encryption-key-volume
        persistentVolumeClaim:
          claimName: hsc-encryption-key-volume
      - name: console-secret
        secret:
          secretName: console-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: console-postgres
  name: console-postgres-int
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: console-postgres
  type: ClusterIP
