apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: console
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
      - image: stackatotest/hsc-console:1.0.52-0-gfd0bbd5
        name: ui
        env:
        - name: HCP_IDENTITY_HOST
          value: console-uaa-int
        - name: HCP_IDENTITY_PORT
          value: "8080"
        - name: HCP_IDENTITY_SCHEME
          value: http
        volumeMounts:
        - mountPath: /etc/secrets/
          name: console-secret
          readOnly: true
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
      - image: stackatotest/hsc-proxy:1.0.534-0-gfd0bbd5
        name: proxy
        env:
        - name: PGSQL_USER
          value: console
        - name: PGSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: console-secret
              key: pgsql-password
        - name: PGSQL_DATABASE
          value: console-db
        - name: PGSQL_HOST
          value: console-postgres-int
        - name: PGSQL_PORT
          value: "5432"
        - name: PGSQL_CONNECT_TIMEOUT_IN_SECS
          value: "100"
        - name: PGSQL_SSL_MODE
          value: disable
        - name: HTTP_CONNECTION_TIMEOUT_IN_SECS
          value: "10"
        - name: HTTP_CLIENT_TIMEOUT_IN_SECS
          value: "20"
        - name: SKIP_TLS_VERIFICATION
          value: "false"
        - name: CONSOLE_PROXY_TLS_ADDRESS
          value: :3003
        - name: CONSOLE_CLIENT
          value: console
        - name: HCE_CLIENT
          value: hce
        - name: HSM_CLIENT
          value: hsm
        - name: HCP_CLIENT
          value: hcp
        - name: HCF_CLIENT
          value: cf
        - name: ALLOWED_ORIGINS
          value: https://localhost
        - name: ENCRYPTION_KEY_VOLUME
          value: hsc-encryption-key-volume
        - name: ENCRYPTION_KEY_FILENAME
          value: key
        - name: HTTP_PROXY
        - name: HTTPS_PROXY
        - name: NO_PROXY
        - name: FTP_PROXY
        - name: SOCKS_PROXY
        - name: HCP_IDENTITY_HOST
          value: console-uaa-int
        - name: HCP_IDENTITY_PORT
          value: "8080"
        - name: HCP_IDENTITY_SCHEME
          value: http
        ports:
        - containerPort: 3003
          name: proxy
          protocol: TCP
        volumeMounts:
        - mountPath: /hsc-upgrade-volume
          name: hsc-upgrade-volume
        - mountPath: /hsc-encryption-key-volume
          name: hsc-encryption-key-volume
        - mountPath: /etc/secrets/
          name: console-secret
          readOnly: true
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres-volume
      - name: hsc-upgrade-volume
        persistentVolumeClaim:
          claimName: hsc-upgrade-volume
      - name: hsc-encryption-key-volume
        persistentVolumeClaim:
          claimName: hsc-encryption-key-volume
      - name: console-secret
        secret:
          secretName: console-secret
---
  kind: Service
  metadata:
    labels:
      app: console
    name: console-ui-ext
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      app: console
    type: NodePort