---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    skiff-role-name: sclr-api
  name: sclr-api
spec:
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: sclr-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        skiff-role-name: sclr-api
      name: sclr-api
    spec:
      containers:
      - env:
        - name: ALLOWED_CORS_DOMAINS
          value: '[]'
        - name: ALLOW_APP_SSH_ACCESS
          value: "true"
        - name: APP_SSH_KEY
          value: |-
{{.Files.Get "ssl/apiSshKey" | indent 12}}
        - name: APP_SSH_KEY_FINGERPRINT
          value: {{.Values.apiSshKeyFingerprint}}
        - name: APP_TOKEN_UPLOAD_GRACE_PERIOD
          value: "1200"
        - name: AUCTIONEER_REP_CERT
          value: |-
{{.Files.Get "ssl/auctioneerRepCert" | indent 12}}
        - name: AUCTIONEER_REP_KEY
          value: |-
{{.Files.Get "ssl/auctioneerRepKey" | indent 12}}
        - name: AUCTIONEER_SERVER_CERT
          value: |-
{{.Files.Get "ssl/auctioneerServerCert" | indent 12}}
        - name: AUCTIONEER_SERVER_KEY
          value: |-
{{.Files.Get "ssl/auctioneerServerKey" | indent 12}}
        - name: AUTOSCALER_COUCHDB_PASSWORD
          value: couchdb_password
        - name: AUTOSCALER_PASSWORD
          value: admin
        - name: BBS_ACTIVE_KEY_PASSPHRASE
          value: key1_passphrase
        - name: BBS_AUCTIONEER_CERT
          value: |-
{{.Files.Get "ssl/bbsAuctioneerCert" | indent 12}}
        - name: BBS_AUCTIONEER_KEY
          value: |-
{{.Files.Get "ssl/bbsAuctioneerKey" | indent 12}}
        - name: BBS_CLIENT_CRT
          value: |-
{{.Files.Get "ssl/bbsClientCrt" | indent 12}}
        - name: BBS_CLIENT_KEY
          value: |-
{{.Files.Get "ssl/bbsClientKey" | indent 12}}
        - name: BBS_REP_CERT
          value: |-
{{.Files.Get "ssl/bbsRepCert" | indent 12}}
        - name: BBS_REP_KEY
          value: |-
{{.Files.Get "ssl/bbsRepKey" | indent 12}}
        - name: BBS_SERVER_CRT
          value: |-
{{.Files.Get "ssl/bbsServerCrt" | indent 12}}
        - name: BBS_SERVER_KEY
          value: |-
{{.Files.Get "ssl/bbsServerKey" | indent 12}}
        - name: BLOBSTORE_ACCESS_RULES
          value: allow 192.0.2.134; allow 10.0.0.0/8; allow 172.16.0.0/12; allow 192.168.0.0/16;
        - name: BLOBSTORE_MAX_UPLOAD_SIZE
          value: "5000"
        - name: BLOBSTORE_PASSWORD
          value: blobstore_password
        - name: BLOBSTORE_SECURE_LINK
          value: blobstore_secure_signing_phrase
        - name: BLOBSTORE_TLS_CERT
          value: |-
{{.Files.Get "ssl/blobstoreTlsCert" | indent 12}}
        - name: BLOBSTORE_TLS_KEY
          value: |-
{{.Files.Get "ssl/blobstoreTlsKey" | indent 12}}
        - name: BULK_API_PASSWORD
          value: password
        - name: CCDB_ROLE_PASSWORD
          value: ccpassword
        - name: CDN_URI
        - name: CF_USB_BROKER_SERVER_CERT
          value: |-
{{.Files.Get "ssl/cfUsbBrokerServerCert" | indent 12}}
        - name: CF_USB_BROKER_SERVER_KEY
          value: |-
{{.Files.Get "ssl/cfUsbBrokerServerKey" | indent 12}}
        - name: CF_USB_PASSWORD
          value: changeme
        - name: CLUSTER_ADMIN_AUTHORITIES
          value: scim.write,scim.read,openid,cloud_controller.admin,clients.read,clients.write,doppler.firehose,routing.router_groups.read
        - name: CLUSTER_ADMIN_PASSWORD
          value: changeme
        - name: CLUSTER_BUILD
          value: 4.0.1
        - name: CLUSTER_DESCRIPTION
          value: HPE Helion Cloud Foundry
        - name: CLUSTER_NAME
          value: HCF
        - name: CLUSTER_VERSION
          value: "2"
        - name: CONSUL_AGENT_CERT
          value: |-
{{.Files.Get "ssl/consulAgentCert" | indent 12}}
        - name: CONSUL_AGENT_KEY
          value: |-
{{.Files.Get "ssl/consulAgentKey" | indent 12}}
        - name: CONSUL_ENCRYPTION_KEYS
          value: 6gAxAGbLRt+b4b0/QpqSvA==
        - name: CONSUL_HCF_CLUSTER_CONFIG_REVISION
          value: "0"
        - name: CONSUL_SERVER_CERT
          value: |-
{{.Files.Get "ssl/consulServerCert" | indent 12}}
        - name: CONSUL_SERVER_KEY
          value: |-
{{.Files.Get "ssl/consulServerKey" | indent 12}}
        - name: DB_ENCRYPTION_KEY
          value: the_key
        - name: DEFAULT_APP_DISK_IN_MB
          value: "1024"
        - name: DEFAULT_APP_MEMORY
          value: "1024"
        - name: DEFAULT_APP_SSH_ACCESS
          value: "true"
        - name: DEMOPHON_SERVER_CERT
          value: |-
{{.Files.Get "ssl/demophonServerCert" | indent 12}}
        - name: DEMOPHON_SERVER_KEY
          value: |-
{{.Files.Get "ssl/demophonServerKey" | indent 12}}
        - name: DIEGO_CELL_MEMORY_CAPACITY_MB
          value: auto
        - name: DIEGO_CELL_NETWORK_MTU
          value: "1400"
        - name: DIEGO_CELL_SUBNET
          value: 10.38.0.0/16
        - name: DISABLE_CUSTOM_BUILDPACKS
          value: "false"
        - name: DNS_HEALTH_CHECK_HOST
          value: example.com.
        - name: DOMAIN
          value: cf-dev.io
        - name: DOPPLER_CERT
          value: |-
{{.Files.Get "ssl/dopplerCert" | indent 12}}
        - name: DOPPLER_KEY
          value: |-
{{.Files.Get "ssl/dopplerKey" | indent 12}}
        - name: DROPLET_MAX_STAGED_STORED
          value: "5"
        - name: ETCD_CLIENT_CRT
          value: |-
{{.Files.Get "ssl/etcdClientCrt" | indent 12}}
        - name: ETCD_CLIENT_KEY
          value: |-
{{.Files.Get "ssl/etcdClientKey" | indent 12}}
        - name: ETCD_HCF_CLUSTER_CONFIG_REVISION
          value: "0"
        - name: ETCD_PEER_CRT
          value: |-
{{.Files.Get "ssl/etcdPeerCrt" | indent 12}}
        - name: ETCD_PEER_KEY
          value: |-
{{.Files.Get "ssl/etcdPeerKey" | indent 12}}
        - name: ETCD_SERVER_CRT
          value: |-
{{.Files.Get "ssl/etcdServerCrt" | indent 12}}
        - name: ETCD_SERVER_KEY
          value: |-
{{.Files.Get "ssl/etcdServerKey" | indent 12}}
        - name: FORCE_FORWARDED_PROTO_AS_HTTPS
          value: "false"
        - name: GARDEN_DOCKER_REGISTRY
          value: registry-1.docker.io
        - name: GARDEN_INSECURE_DOCKER_REGISTRIES
        - name: GARDEN_LINUX_DNS_SERVER
          value: 10.0.0.10
        - name: HAPROXY_SSL_CERT_KEY
          value: |-
{{.Files.Get "ssl/haproxySslCertKey" | indent 12}}
        - name: HCF_SSO_OAUTH_ID
          value: hcf-sso
        - name: HCF_SSO_PASSWORD
          value: hcf_sso_secret
        - name: HCP_CA_CERT
          value: |-
{{.Files.Get "ssl/hcpCaCert" | indent 12}}
        - name: HCP_SERVICE_DOMAIN_SUFFIX
          value: ${namespace}.svc.cluster.local
        - name: INTERNAL_API_PASSWORD
          value: internal_password
        - name: INTERNAL_CA_CERT
          value: |-
{{.Files.Get "ssl/internalCaCert" | indent 12}}
        - name: JWT_SIGNING_PEM
          value: |-
{{.Files.Get "ssl/jwtSigningPem" | indent 12}}
        - name: JWT_SIGNING_PUB
          value: |-
{{.Files.Get "ssl/jwtSigningPub" | indent 12}}
        - name: LOGGREGATOR_SHARED_SECRET
          value: loggregator_endpoint_secret
        - name: LOG_LEVEL
          value: debug
        - name: MAX_APP_DISK_IN_MB
          value: "2048"
        - name: MAX_HEALTH_CHECK_TIMEOUT
          value: "180"
        - name: METRON_CERT
          value: |-
{{.Files.Get "ssl/metronCert" | indent 12}}
        - name: METRON_KEY
          value: |-
{{.Files.Get "ssl/metronKey" | indent 12}}
        - name: MONIT_PASSWORD
          value: monit_password
        - name: MYSQL_ADMIN_PASSWORD
          value: mysql_admin_password
        - name: MYSQL_CF_USB_PASSWORD
          value: mysql_cf_usb_password
        - name: MYSQL_DIEGO_PASSWORD
          value: mysql_diego_password
        - name: NATS_HCF_CLUSTER_CONFIG_REVISION
          value: "0"
        - name: NATS_PASSWORD
          value: nats_password
        - name: NGINX_MAX_REQUEST_BODY_SIZE
          value: "1536"
        - name: PERSI_BROKER_PASSWORD
          value: admin
        - name: REP_SERVER_CERT
          value: |-
{{.Files.Get "ssl/repServerCert" | indent 12}}
        - name: REP_SERVER_KEY
          value: |-
{{.Files.Get "ssl/repServerKey" | indent 12}}
        - name: RESERVABLE_PORTS
          value: 20000-20008
        - name: ROOTFS_TRUSTED_CERTS
        - name: ROUTER_BALANCING_ALGORITHM
          value: round-robin
        - name: ROUTER_SERVICES_SECRET
          value: router_secret
        - name: ROUTER_SSL_CERT
          value: |-
{{.Files.Get "ssl/routerSslCert" | indent 12}}
        - name: ROUTER_SSL_KEY
          value: |-
{{.Files.Get "ssl/routerSslKey" | indent 12}}
        - name: ROUTER_STATUS_PASSWORD
          value: router_status_password
        - name: SAML_SERVICEPROVIDER_CERT
          value: |-
{{.Files.Get "ssl/samlServiceProviderCert" | indent 12}}
        - name: SAML_SERVICEPROVIDER_KEY
          value: |-
{{.Files.Get "ssl/samlServiceProviderKey" | indent 12}}
        - name: SKIP_CERT_VERIFY_EXTERNAL
          value: "false"
        - name: SKIP_CERT_VERIFY_INTERNAL
          value: "false"
        - name: SSO_ROUTE_CERT
          value: |-
{{.Files.Get "ssl/ssoRouteCert" | indent 12}}
        - name: SSO_ROUTE_KEY
          value: |-
{{.Files.Get "ssl/ssoRouteKey" | indent 12}}
        - name: STAGER_INSECURE_DOCKER_REGISTRIES
        - name: STAGING_TIMEOUT
          value: "900"
        - name: STAGING_UPLOAD_PASSWORD
          value: password
        - name: SUPPORT_ADDRESS
          value: stackato-support@hpe.com
        - name: TCP_DOMAIN
          value: tcp.cf-dev.io
        - name: TRAFFICCONTROLLER_CERT
          value: |-
{{.Files.Get "ssl/trafficcontrollerCert" | indent 12}}
        - name: TRAFFICCONTROLLER_KEY
          value: |-
{{.Files.Get "ssl/trafficcontrollerKey" | indent 12}}
        - name: TRUSTED_CERTS
        - name: UAADB_PASSWORD
          value: uaaadmin_password
        - name: UAA_ADMIN_CLIENT_SECRET
          value: admin_secret
        - name: UAA_CC_CLIENT_SECRET
          value: cc_client_secret
        - name: UAA_CLIENTS_CC_ROUTING_SECRET
          value: cc_routing_secret
        - name: UAA_CLIENTS_CC_SERVICE_SECRET
          value: cc_service_secret
        - name: UAA_CLIENTS_CF_AUTOSCALER_SECRET
          value: cf-autoscaler-client-secret
        - name: UAA_CLIENTS_CF_USB_SECRET
          value: cf_usb_secret
        - name: UAA_CLIENTS_CLOUD_CONTROLLER_USERNAME_LOOKUP_SECRET
          value: cloud_controller_username_lookup_secret
        - name: UAA_CLIENTS_DIEGO_SSH_PROXY_SECRET
          value: ssh_proxy_secret
        - name: UAA_CLIENTS_DOPPLER_SECRET
          value: doppler_secret
        - name: UAA_CLIENTS_GOROUTER_SECRET
          value: gorouter_secret
        - name: UAA_CLIENTS_HCF_AUTO_CONFIG_SECRET
          value: uaa_client_hcf_auto_config_secret
        - name: UAA_CLIENTS_HCF_SSO_SECRET
          value: hcf_sso_secret
        - name: UAA_CLIENTS_LOGIN_SECRET
          value: login_client_secret
        - name: UAA_CLIENTS_TCP_EMITTER_SECRET
          value: uaa_client_tcp_emitter_secret
        - name: UAA_CLIENTS_TCP_ROUTER_SECRET
          value: uaa_client_tcp_router_secret
        - name: UAA_SERVER_CERT
          value: |-
{{.Files.Get "ssl/uaaServerCert" | indent 12}}
        - name: UAA_SERVER_KEY
          value: |-
{{.Files.Get "ssl/uaaServerKey" | indent 12}}
        - name: USE_DIEGO_PRIVILEGED_CONTAINERS
          value: "false"
        - name: USE_STAGER_PRIVILEGED_CONTAINERS
          value: "false"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry.paas-ui:5000/fissile-sclr-api:d4bf0051035f731386924d090e921c0383301931
        livenessProbe:
          initialDelaySeconds: 600
          tcpSocket:
            port: 2289
        name: sclr-api
        ports:
        - containerPort: 28861
          name: api
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 28861
            scheme: HTTP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: sclr-api
spec:
  ports:
  - name: api
    port: 28861
    protocol: TCP
    targetPort: api
  selector:
    skiff-role-name: sclr-api
  type: ClusterIP
status:
  loadBalancer: {}
