---
platform: linux
inputs:
- name: stratos-deploy
- name: portal-proxy-output
  path: src/github.com/hpcloud/portal-proxy
- name: stratos-ui
image_resource:
  type: docker-image
  source:
    repository: "10.4.21.241:5000/stackatotest/hsc-dcind"
    tag: "latest"
    insecure_registries: ["10.4.21.241:5000"]
run:
  path: sh
  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      docker info
      export GOPATH=$PWD
      cd stratos-deploy
      # Load images from image
      for image in $(ls /docker-images); do
        docker load -i /docker-images/${image};
      done
      COMPOSE_HTTP_TIMEOUT=300 docker-compose -f docker-compose.test.yml build
      COMPOSE_HTTP_TIMEOUT=300 docker-compose -f docker-compose.test.yml up -d
      docker logs -f stratosdeploy_ui_1
      sh ./ci/scripts/check_tests.sh
