resources:
- name: stratos-deploy
  type: git
  source:
    uri: git@github.com:hpcloud/stratos-deploy.git
    branch: {{stratos-deploy-branch}}
    private_key: {{github-private-key}}
- name: portal-proxy
  type: git
  source:
    uri: git@github.com:hpcloud/portal-proxy.git
    branch:  {{portal-proxy-branch}}
    private_key: {{github-private-key}}
- name: stratos-ui
  type: git
  source:
    branch: {{stratos-ui-branch}}
    private_key: {{github-private-key}}
    uri: git@github.com:hpcloud/stratos-ui.git

jobs:
- name: console-tests
  plan:
  - get: stratos-deploy
  - get: portal-proxy
  - get: stratos-ui

  - do:
    - task: run-unit-tests
      privileged: true
      timeout: 5m
      file: stratos-deploy/ci/tasks/stratos-ui/run-unit-tests.yml
    - task: build-proxy-image
      file: stratos-deploy/ci/tasks/stratos-ui/prep-proxy-image.yml
    - task: run-e2e-tests
      privileged: true
      params:
       REGISTRY_NAME: {{insecure-registry}}
       CUSTOM_APP_LABEL: {{custom-app-label}}
      timeout: 10m
      file: stratos-deploy/ci/tasks/stratos-ui/run-tests.yml
