---
# Helion Stackato Console UI (stratos)

resources:

  # versioning
  - name: resource-version
    type: semver
    source:
      driver: s3
      initial_version: 0.0.1
      bucket: {{s3-version-bucket}}
      key: {{s3-version-key}}
      access_key_id: {{s3-access-key}}
      secret_access_key: {{s3-secret}}
      region_name: {{s3-region-name}}

  # git repos
  - name: helion-ui-theme
    type: git
    source:
      uri: git@github.com:hpcloud/helion-ui-theme.git
      branch: master
      private_key: {{github-private-key}}
  - name: helion-ui-framework
    type: git
    source:
      uri: git@github.com:hpcloud/helion-ui-framework.git
      branch: master
      private_key: {{github-private-key}}
  - name: stratos-ui
    type: git
    source:
      uri: git@github.com:hpcloud/stratos-ui.git
      branch: master
      private_key: {{github-private-key}}
  - name: portal-proxy
    type: git
    source:
      uri: git@github.com:hpcloud/portal-proxy.git
      branch: master
      private_key: {{github-private-key}}
  - name: stratos-deploy
    type: git
    source:
      uri: git@github.com:hpcloud/stratos-deploy.git
      branch: master
      private_key: {{github-private-key}}

  # docker images
  - name: stratos-server-image
    type: docker-image
    source:
      repository: docker-registry.helion.space:443/helioncf/cnap-console-server
  - name: portal-proxy-image
    type: docker-image
    source:
      repository: docker-registry.helion.space:443/helioncf/cnap-console-proxy
  - name: database-config-image
    type: docker-image
    source:
      repository: docker-registry.helion.space:443/helioncf/cnap-console-database-configuration

  # HSM assets
  - name: hsm-sdl-bucket
    type: s3
    source:
      bucket: {{s3-hsm-bucket}}
      versioned_file: {{s3-hsm-sdl}}
      access_key_id: {{s3-access-key}}
      secret_access_key: {{s3-secret}}
      region_name: {{s3-region-name}}
  - name: hsm-instance-bucket
    type: s3
    source:
      bucket: {{s3-hsm-bucket}}
      versioned_file: {{s3-hsm-instance}}
      access_key_id: {{s3-access-key}}
      secret_access_key: {{s3-secret}}
      region_name: {{s3-region-name}}
  - name: hsm-hcp-version-bucket
    type: s3
    source:
      bucket: {{s3-hsm-bucket}}
      versioned_file: {{s3-hsm-hcp-version}}
      access_key_id: {{s3-access-key}}
      secret_access_key: {{s3-secret}}
      region_name: {{s3-region-name}}

jobs:
  - name: build-console
    serial: true
    plan:

    # Get the current version, bump the patch level
    - get: resource-version
      params: {bump: patch}
    - put: resource-version
      params: {file: resource-version/number}

    # Get GH resources
    - get: stratos-deploy
      trigger: true
    - get: portal-proxy
      trigger: true
    - get: helion-ui-theme
      trigger: true
    - get: helion-ui-framework
      trigger: true
    - get: stratos-ui
      trigger: true

    #  Generate tag/version file
    - task: generate-tag-files
      file: stratos-deploy/ci/tasks/build-tag-file.yml

    # Build the Portal Proxy image, push to registry
    - task: build-proxy-image
      file: stratos-deploy/ci/tasks/build-proxy-image.yml
    - put: portal-proxy-image
      params:
        dockerfile: portal-proxy-output/Dockerfile.UCP
        build: portal-proxy-output
        tag: tag-files/version_tag

    # Build the database configuration image, push to registry
    - put: database-config-image
      params:
        dockerfile: portal-proxy-output/Dockerfile.database.UCP
        build: portal-proxy-output
        tag: tag-files/version_tag

    # Build the Stackato UI image, push to registry
    - task: build-ui-image
      file: stratos-deploy/ci/tasks/build-ui-image.yml
    - put: stratos-server-image
      params:
        dockerfile: stratos-server-output/Dockerfile.HCP
        build: stratos-server-output
        tag: tag-files/version_tag

    # Push out the HSM configs
    - task: build-hsm-configs
      file: stratos-deploy/ci/tasks/build-hsm-configs.yml
      params:
        registry: {{registry}}
    - put: hsm-sdl-bucket
      params:
        file: stratos-deploy-output/sdl.json
        acl: public-read
    - put: hsm-instance-bucket
      params:
        file: stratos-deploy-output/instance.json
        acl: public-read
    - put: hsm-hcp-version-bucket
      params:
        file: stratos-deploy-output/hcp_version
        acl: public-read

    # Tag all repos with the current version
    - put: stratos-deploy
      params:
        repository: stratos-deploy
        tag: tag-files/version_tag
        only_tag: true
    - put: portal-proxy
      params:
        repository: portal-proxy
        tag: tag-files/version_tag
        only_tag: true
    - put: helion-ui-theme
      params:
        repository: helion-ui-theme
        tag: tag-files/version_tag
        only_tag: true
    - put: helion-ui-framework
      params:
        repository: helion-ui-framework
        tag: tag-files/version_tag
        only_tag: true
    - put: stratos-ui
      params:
        repository: stratos-ui
        tag: tag-files/version_tag
        only_tag: true
