---
# Helion Stackato Console UI (stratos)

resources:

  # versioning
  - name: resource-version
    type: semver
    source:
      driver: s3
      initial_version: 0.0.1
      bucket: {{s3-version-bucket}}
      key: {{s3-version-key}}
      access_key_id: {{s3-access-key}}
      secret_access_key: {{s3-secret}}
      region_name: {{s3-region-name}}

  # git repos
  - name: helion-ui-framework
    type: git
    source:
      uri: git@github.com:hpcloud/helion-ui-framework.git
      branch: master
      private_key: {{github-private-key}}
  - name: stratos-ui
    type: git
    source:
      uri: git@github.com:hpcloud/stratos-ui.git
      branch: master
      private_key: {{github-private-key}}
  - name: portal-proxy
    type: git
    source:
      uri: git@github.com:hpcloud/portal-proxy.git
      branch: master
      private_key: {{github-private-key}}
  - name: stratos-deploy
    type: git
    source:
      uri: git@github.com:hpcloud/stratos-deploy.git
      branch: master
      private_key: {{github-private-key}}

  # docker images
  - name: hsc-console-image
    type: docker-image
    source:
      repository: docker-registry.helion.space:443/hsc/hsc-console
  - name: hsc-proxy-image
    type: docker-image
    source:
      repository: docker-registry.helion.space:443/hsc/hsc-proxy
  - name: hsc-etcd2-image
    type: docker-image
    source:
      repository: docker-registry.helion.space:443/hsc/hsc-etcd2
  - name: hsc-stolon-image
    type: docker-image
    source:
      repository: docker-registry.helion.space:443/hsc/hsc-stolon
  - name: hsc-preflight-job-image
    type: docker-image
    source:
      repository: docker-registry.helion.space:443/hsc/hsc-preflight-job
  - name: hsc-postflight-job-image
    type: docker-image
    source:
      repository: docker-registry.helion.space:443/hsc/hsc-postflight-job

jobs:
  - name: build-console
    serial: true
    plan:

    # Get the current version, bump the patch level
    - get: resource-version
      params: {bump: patch}
    - put: resource-version
      params: {file: resource-version/number}

    # Get GH resources
    - get: stratos-deploy
      trigger: true
    - get: portal-proxy
      trigger: true
    - get: helion-ui-framework
      trigger: true
    - get: stratos-ui
      trigger: true

    #  Generate tag/version file
    - task: generate-tag-files
      file: stratos-deploy/ci/tasks/build-tag-file.yml

    # Build the Portal Proxy image, push to registry
    - task: build-proxy-image
      file: stratos-deploy/ci/tasks/build-proxy-image.yml
    - put: hsc-proxy-image
      params:
        dockerfile: portal-proxy-output/Dockerfile.HCP
        build: portal-proxy-output
        tag: tag-files/version_tag

    # Build the etcd2 image, push to registry
    - put: hsc-etcd2-image
      params:
        dockerfile: portal-proxy-output/containers/etcd2/Dockerfile.HCP
        build: portal-proxy-output
        tag: tag-files/version_tag

    # Build the stolon image, push to registry
    - put: hsc-stolon-image
      params:
        dockerfile: portal-proxy-output/containers/stolon/Dockerfile.HCP
        build: portal-proxy-output
        tag: tag-files/version_tag

    # Build the preflight image, push to registry
    - put: hsc-preflight-job-image
      params:
        dockerfile: portal-proxy-output/db/Dockerfile.preflight-job.HCP
        build: portal-proxy-output
        tag: tag-files/version_tag

    # Build the postflight image, push to registry
    - put: hsc-postflight-job-image
      params:
        dockerfile: portal-proxy-output/db/Dockerfile.postflight-job.HCP
        build: portal-proxy-output
        tag: tag-files/version_tag

    # Build the Stackato UI image, push to registry
    - task: build-ui-image
      file: stratos-deploy/ci/tasks/build-ui-image.yml
    - put: hsc-console-image
      params:
        dockerfile: stratos-server-output/Dockerfile.HCP
        build: stratos-server-output
        tag: tag-files/version_tag

    # Tag all repos with the current version
    - put: stratos-deploy
      params:
        repository: stratos-deploy
        tag: tag-files/version_tag
        only_tag: true
    - put: portal-proxy
      params:
        repository: portal-proxy
        tag: tag-files/version_tag
        only_tag: true
    - put: helion-ui-framework
      params:
        repository: helion-ui-framework
        tag: tag-files/version_tag
        only_tag: true
    - put: stratos-ui
      params:
        repository: stratos-ui
        tag: tag-files/version_tag
        only_tag: true
