resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: stratos-deploy
  type: git
  source:
    uri: git@github.com:hpcloud/stratos-deploy.git
    branch: master
    private_key: {{github-private-key}}
- name: portal-proxy
  type: git
  source:
    uri: git@github.com:hpcloud/portal-proxy.git
    branch: master
    private_key: {{github-private-key}}
- name: stratos-ui
  type: pull-request
  source:
    access_token: {{github-access-token}}
    repo: hpcloud/stratos-ui
    uri: git@github.com:hpcloud/stratos-ui.git
    private_key: {{github-private-key}}

jobs:
- name: console-tests
  plan:
  - get: stratos-deploy
  - get: portal-proxy

  # get PR and set status to pending
  - get: stratos-ui
    trigger: true
  - put: stratos-ui
    params:
      path: stratos-ui
      status: pending

  - do:
    - task: run-unit-tests
      privileged: true
      timeout: 5m
      file: stratos-deploy/ci/tasks/stratos-ui/run-unit-tests.yml
      on_failure:
        put: stratos-ui
        params:
          path: stratos-ui
          status: failure
    - task: build-proxy-image
      file: stratos-deploy/ci/tasks/stratos-ui/prep-proxy-image.yml
    - task: run-e2e-tests
      privileged: true
      timeout: 10m
      file: stratos-deploy/ci/tasks/stratos-ui/run-tests.yml
      on_success:
        put: stratos-ui
        params:
          path: stratos-ui
          status: success
      on_failure:
        put: stratos-ui
        params:
          path: stratos-ui
          status: failure

