resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: stratos-deploy
  type: git
  source:
    uri: git@github.com:hpcloud/stratos-deploy.git
    branch: master
    private_key: {{github-private-key}}
- name: portal-proxy
  type: git
  source:
    uri: git@github.com:hpcloud/portal-proxy.git
    branch: master
    private_key: {{github-private-key}}
- name: stratos-ui
  type: pull-request
  source:
    access_token: {{github-access-token}}
    repo: hpcloud/stratos-ui
    uri: git@github.com:hpcloud/stratos-ui.git
    private_key: {{github-private-key}}
- name: helion-ui-theme
  type: git
  source:
    uri: git@github.com:hpcloud/helion-ui-theme.git
    branch: master
    private_key: {{github-private-key}}
- name: helion-ui-framework
  type: git
  source:
    uri: git@github.com:hpcloud/helion-ui-framework.git
    branch: master
    private_key: {{github-private-key}}

jobs:
- name: console-ui-tests
  plan:
  # get dependencies
  - get: stratos-deploy
  - get: portal-proxy
  - get: helion-ui-theme
  - get: helion-ui-framework

  # get PR and set status to pending
  - get: stratos-ui
    trigger: true
  - put: stratos-ui
    params:
      path: stratos-ui
      status: pending

  # Build the Portal Proxy image
  - task: build-proxy-image
    file: stratos-deploy/ci/tasks/stratos-ui/prep-proxy-image.yml
    params:
      GITHUB_OAUTH_CLIENT_ID: {{github-oauth-client-id}}
      GITHUB_OAUTH_CLIENT_SECRET: {{github-oauth-client-secret}}

  # install libraries and run tests
  - task: run-tests
    privileged: true
    timeout: 45m
    file: stratos-deploy/ci/tasks/stratos-ui/run-tests.yml
    params:
      GITHUB_OAUTH_CLIENT_ID: {{github-oauth-client-id}}
      GITHUB_OAUTH_CLIENT_SECRET: {{github-oauth-client-secret}}
    on_success:
      put: stratos-ui
      params:
        path: stratos-ui
        status: success
    on_failure:
      put: stratos-ui
      params:
        path: stratos-ui
        status: failure
